### ISSUE TITLE
Changing gravity (may) crash with a System.IO.IOException.

### ISSUE THREAD

**Issue by PinkDev1** [max4805/Everest-ExtendedVariants#2]
Crash (may) happen after changing the gravity value under menu->extended variants->movement->gravity.
The error does not seem to be related to "[CrossoverMod](https://gamebanana.com/skins/166689)", as it still happens after deleting the mod.
Keep in mind that the error happens even if CrossoverMod is turned off in ModSettings.

Error log:
```
Ver 1.3.1.2 [Everest: 1697-azure-76974]
05/25/2020 19:26:51
System.IO.IOException: The process cannot access the file 'C:\Program Files\Celeste Farewell\Saves\modsettings-CrossoverMod.celeste' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at Celeste.Mod.EverestModule.SaveSettings() in D:\a\1\s\Celeste.Mod.mm\Mod\Module\EverestModule.cs:line 82
   at Celeste.Mod.Everest.c__DisplayClass58_0.b__0() in D:\a\1\s\Celeste.Mod.mm\Mod\Everest\Everest.cs:line 661
   at Celeste.RunThread.RunThreadWithLogging(Action method) in D:\a\1\s\Celeste.Mod.mm\Patches\RunThread.cs:line 41
```

Error log after deleting CrossoverMod:
```
Ver 1.3.1.2 [Everest: 1697-azure-76974]
05/25/2020 20:46:01
System.IO.IOException: The process cannot access the file 'C:\Program Files\Celeste Farewell\Saves\modsettings-DeathMarkers.celeste' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at Celeste.Mod.EverestModule.SaveSettings() in D:\a\1\s\Celeste.Mod.mm\Mod\Module\EverestModule.cs:line 82
   at Celeste.Mod.Everest.<>c__DisplayClass58_0.<_SaveSettings>b__0() in D:\a\1\s\Celeste.Mod.mm\Mod\Everest\Everest.cs:line 661
   at Celeste.RunThread.RunThreadWithLogging(Action method) in D:\a\1\s\Celeste.Mod.mm\Patches\RunThread.cs:line 41
```

**Comment by max4805** [comment]
Is that an issue you can replicate easily? If so, when exactly does it happen? (I would assume when pressing Back from the Movement screen?) 

I'd like to try replicating the crash to be able to test if the fix I'm thinking about is effective or not without having you to test it out each time. 😅

**Comment by PinkDev1** [comment]
Yep, sadly, it's easy to replicate. It happens after you change the gravity value and go back to the game (Press back three times).

**Comment by max4805** [comment]
I still couldn't replicate myself :/ the crash apparently happens while saving all mods' settings, which happens when exiting out of the "extended variants" menu. I tried changing this to saving only the settings for extended variants, would you mind trying this out? 😅 

[ExtendedVariantMode-DevBuild.zip](https://github.com/max4805/Everest-ExtendedVariants/files/4692028/ExtendedVariantMode-DevBuild.zip)

**Comment by PinkDev1** [comment]
I (re)moved the old _ExtendedVariantMode.zip_ file and replaced it with the one you published.
**Well done** @max4805! I can no longer reproduce the issue 👍 
Also, going back from that menu (saving) is now notoriously faster (Probably bc I have plenty of mods)
![image](https://user-images.githubusercontent.com/46269721/83079583-8d809c80-a052-11ea-8335-8f0205331eb3.png)

**Comment by max4805** [comment]
Thanks for the quick testing! I just published that new version on GameBanana.
